// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Process = require("process");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Mail = require("@sendgrid/mail");
var Api$PlantSaver = require("./Api.bs.js");

var to_ = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["EMAIL_TO"]));

var from = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["EMAIL_FROM"]));

var user_000 = /* id : UserId */["1"];

var user_001 = /* email : Email */[to_];

var user_002 = /* password : Password */["1"];

var user = /* record */[
  user_000,
  user_001,
  user_002
];

var plant_000 = /* id : PlantId */["Habanero"];

var plant_001 = /* owner : UserId */["1"];

var plant_002 = /* location : record */[
  /* zip : ZipDe */["40239"],
  /* country : DE */0
];

var plant_003 = /* threshold : Celsius */Block.__(1, [15.0]);

var plant = /* record */[
  plant_000,
  plant_001,
  plant_002,
  plant_003
];

function needsSaving(plant, tomorrow) {
  var match = plant[/* threshold */3];
  if (match.tag) {
    if (tomorrow[/* main */0][/* temp_min */2] - 272.15 < match[0]) {
      return /* Some */["Hol sie rein es werden " + (tomorrow[/* main */0][/* temp_min */2] - 272.15).toString()];
    } else {
      return /* None */0;
    }
  } else if (tomorrow[/* main */0][/* temp_min */2] < match[0]) {
    return /* Some */["Hol sie rein es werden " + tomorrow[/* main */0][/* temp_min */2].toString()];
  } else {
    return /* None */0;
  }
}

function command(forecasts) {
  return Belt_Option.getWithDefault(Belt_Option.flatMap(Api$PlantSaver.tomorrowNight(forecasts), (function (param) {
                    return needsSaving(plant, param);
                  })), "Kann draussen bleiben");
}

var appid = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["APPID"]));

var apikey = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["SENDGRID_API_KEY"]));

Mail.setApiKey(apikey);

Api$PlantSaver.forecast(appid, plant).then((function (forecasts) {
          return Promise.resolve(command(forecasts));
        })).then((function (cmd) {
        var msg = {
          to: to_,
          from: from,
          subject: "Plant Status",
          text: cmd,
          html: cmd
        };
        return Promise.resolve(Mail.send(msg));
      }));

exports.to_ = to_;
exports.from = from;
exports.user = user;
exports.plant = plant;
exports.needsSaving = needsSaving;
exports.command = command;
exports.appid = appid;
exports.apikey = apikey;
/* to_ Not a pure module */
