// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Api$PlantSaver = require("./Api.bs.js");

var plant = /* record */[
  /* location : record */[
    /* zip : ZipDe */["40239"],
    /* country : DE */0
  ],
  /* threshold : Celsius */Block.__(1, [15.0])
];

function isSafe(plant, tomorrow) {
  var match = plant[/* threshold */1];
  if (match.tag) {
    if (tomorrow[/* main */0][/* temp_min */2] - 272.15 < match[0]) {
      return /* Some */["Hol sie rein es werden " + (tomorrow[/* main */0][/* temp_min */2] - 272.15).toString()];
    } else {
      return /* None */0;
    }
  } else if (tomorrow[/* main */0][/* temp_min */2] < match[0]) {
    return /* Some */["Hol sie rein es werden " + tomorrow[/* main */0][/* temp_min */2].toString()];
  } else {
    return /* None */0;
  }
}

function command(forecasts) {
  return Belt_Option.getWithDefault(Belt_Option.flatMap(Api$PlantSaver.tomorrowNight(forecasts), (function (param) {
                    return isSafe(plant, param);
                  })), "Kann draussen bleiben");
}

Api$PlantSaver.forecast(plant).then((function (forecasts) {
          return Promise.resolve(command(forecasts));
        })).then((function (cmd) {
        return Promise.resolve((console.log(cmd), /* () */0));
      }));

exports.plant = plant;
exports.isSafe = isSafe;
exports.command = command;
/*  Not a pure module */
