// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Api$PlantSaver = require("./Api.bs.js");

var plant = /* record */[
  /* location : record */[
    /* zip : ZipDe */["40239"],
    /* country : DE */0
  ],
  /* threshold : Celsius */Block.__(1, [15.0])
];

Api$PlantSaver.forecast(plant).then((function (forecasts) {
          return Promise.resolve(Api$PlantSaver.tomorrow(forecasts));
        })).then((function (tomorrow) {
        if (tomorrow) {
          var main = tomorrow[0];
          if (main[/* main */0][/* temp_min */2] - 272.15 < 15.0) {
            console.log("Hol sie rein es werden " + (main[/* main */0][/* temp_min */2] - 272.15).toString());
          } else {
            console.log("alles fein");
          }
          return Promise.resolve("");
        } else {
          return Promise.resolve("");
        }
      }));

exports.plant = plant;
/*  Not a pure module */
