// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Process = require("process");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Mail = require("@sendgrid/mail");
var Api$PlantSaver = require("./Api.bs.js");

var plant = /* record */[
  /* location : record */[
    /* zip : ZipDe */["40239"],
    /* country : DE */0
  ],
  /* threshold : Celsius */Block.__(1, [15.0])
];

function needsSaving(plant, tomorrow) {
  var match = plant[/* threshold */1];
  if (match.tag) {
    if (tomorrow[/* main */0][/* temp_min */2] - 272.15 < match[0]) {
      return /* Some */["Hol sie rein es werden " + (tomorrow[/* main */0][/* temp_min */2] - 272.15).toString()];
    } else {
      return /* None */0;
    }
  } else if (tomorrow[/* main */0][/* temp_min */2] < match[0]) {
    return /* Some */["Hol sie rein es werden " + tomorrow[/* main */0][/* temp_min */2].toString()];
  } else {
    return /* None */0;
  }
}

function command(forecasts) {
  return Belt_Option.getWithDefault(Belt_Option.flatMap(Api$PlantSaver.tomorrowNight(forecasts), (function (param) {
                    return needsSaving(plant, param);
                  })), "Kann draussen bleiben");
}

var appid = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["APPID"]));

var apikey = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["SENDGRID_API_KEY"]));

var to_ = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["EMAIL_TO"]));

var from = Belt_Option.getExn(Js_primitive.undefined_to_opt(Process.env["EMAIL_FROM"]));

Mail.setApiKey(apikey);

Api$PlantSaver.forecast(appid, plant).then((function (forecasts) {
          return Promise.resolve(command(forecasts));
        })).then((function (cmd) {
        var msg = {
          to: to_,
          from: from,
          subject: "Plant Status",
          text: cmd,
          html: cmd
        };
        return Promise.resolve((Mail.send(msg), /* () */0));
      }));

exports.plant = plant;
exports.needsSaving = needsSaving;
exports.command = command;
exports.appid = appid;
exports.apikey = apikey;
exports.to_ = to_;
exports.from = from;
/* appid Not a pure module */
