// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function countryToString() {
  return "de";
}

function zipToString(zip) {
  return zip[0];
}

exports.countryToString = countryToString;
exports.zipToString = zipToString;
/* No side effect */
